### PR TITLE
Create SR15v full report

### PR DESCRIPTION
**Pull request by timinclimate**
Per my discussion with Zeb, here are a few bib files for SR15

### CODE REVIEW

**Comment by rgieseke** [comment]
Awesome, many thanks @tabaxter !

How about changing the identifiers to something in line with the AR5 items, e.g. something like

@book{IPCC_2018_SR15,

@inbook{IPCC_2018_SR15_Ch_2,

We can also do this later, after merging - thoughts @znicholls?

**Comment by znicholls** [comment]
Wicked. Unifying names before merge would be great, not essential though.

**Comment by timinclimate** [comment]
I'm happy to do that. I just exported from Zotero, so I confess I didn't look at what it had put in there.

________________________________

**Comment by timinclimate** [comment]
Done. 

(I think...? I don't use github often, so let me know if there's anything else I need to do to commit the changes.)

**Comment by znicholls** [comment]
Perfect from my end @tabaxter. @rgieseke hit the button when you're happy (we can rename, put all the citations in one file and change incollection{@inbook to @inbook after merging)

**Comment by znicholls** [comment]
> here are a few bib files for SR15

@tabaxter did you want to add more than one file (maybe I'm being thick but I can only see one...)

**Comment by znicholls** [comment]
> @tabaxter did you want to add more than one file (maybe I'm being thick but I can only see one...)

I am being thick, I have just seen #12 and #13

**Comment by rgieseke** [comment]
Awesome, thanks!

**Pull request merged**
