### PR TITLE
Complete the AR6 WG3 bib file

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by jkikstra** [comment]
Thanks @pitmonticone for doing this and adding the other chapters! 

Looks good to me. 

Even if AR6 WG1 and AR6 WG2 now have downloadable bibtex (which we could update to), WG3 still does not yet have them: see #25 


So in light of that, I think we can merge -- @rgieseke  ?

**Comment by rgieseke** [comment]
Thanks @pitmonticone for adding these!
Thanks for the review @jkikstra!

**Comment by pitmonticone** [comment]
Hi @jkikstra and @rgieseke, thank you very much for reviewing and merging this PR. 

I've taken a look at [IPCC_AR6_WGI_Citation.bib](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Citation.bib) and many chapter-specific items seem to lack important entries such as `chapter` and `url`: 

```bib
@inbook{RN26,
   author = {Ranasinghe, R. and Ruane, A.C. and Vautard, R. and Arnell, N. and Coppola, E. and Cruz, F.A. and Dessai, S. and Islam, A.S. and Rahimi, M. and Ruiz Carrascal, D.  and Sillmann, J. and Sylla, M.B. and Tebaldi, C. and Wang, W. and Zaaboul, R.},
   title = {Climate Change Information for Regional Impact and for Risk Assessment},
   booktitle = {Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change},
   editor = {Masson-Delmotte, V.  and Zhai, P. and Pirani, A. and Connors, S.L. and Péan, C. and Berger, S. and Caud, N. and Chen, Y. and Goldfarb, L. and Gomis, M.I. and Huang, M. and Leitzell, K. and Lonnoy, E. and Matthews, J.B.R. and Maycock, T.K. and Waterfield, T. and Yelekçi, O. and Yu, R. and Zhou, B.},
   publisher = {Cambridge University Press},
   address = {Cambridge, United Kingdom and New York, NY, USA},
   pages = {1767–1926},
   DOI = {10.1017/9781009157896.014},
   year = {2021},
   type = {Book Section}
```

I believe it could be useful to have clean and complete files for all WGs. If you agree I can standardise at least the AR6 files in the next few days when I find the time. 

**PS**: Should we adopt `@inbook` or `@incollection`?

**Comment by rgieseke** [comment]
> I believe it could be useful to have clean and complete files for all WGs. If you agree I can standardise at least the AR6 files in the next few days when I find the time.

That would be much appreciated!

> PS: Should we adopt @inbook or @incollection?

I have no insights into this but we changed this here I believe:

https://github.com/openclimatedata/ipcc-bibtex/pull/22

**Comment by pitmonticone** [comment]
> That would be much appreciated!

Great @rgieseke, let me know if you believe it could be helpful if I join this GitHub organisation as a member. 

> I have no insights into this but we changed this here I believe:
> #22

Ok, I will use `@incollection` then.

**Pull request merged**
