### PR TITLE
Add WG III BibTeX entry

### PR DESCRIPTION
**Pull request by rgieseke**

### CODE REVIEW

**Comment by znicholls** [comment]
do we want subfolders, `IPCC-assessment-reports/WGIII/full.tex`

**Comment by znicholls** [comment]
> do we want subfolders, `IPCC-assessment-reports/WGIII/full.tex`

Having seen #5, maybe just `IPCC-assessment-reports/WGIII`?

**Comment by rgieseke** [comment]
What else could be added? If it's only IPCC reports i don't think we'd need subfolders.

**Comment by znicholls** [comment]
> What else could be added?

Good point, I have no idea so we cross that bridge when we come to it

**Review by znicholls — APPROVED** [review]

**Pull request merged**
