### PR TITLE
adding sres-wg-iii, augmenting ar4-wg-i

### LINKED ISSUE #38: Add Special Report on Emissions Scenarios (SRES); Augment AR4 with multiple chapters
This should be identified as sres-wg-iii.bib

Findable at [full report (6 Chapters, plus ~300 pages of appendices [black and white, not a great copy])](https://www.ipcc.ch/site/assets/uploads/2018/03/emissions_scenarios-1.pdf) and [summary for policymakers (SPM [colour])](https://www.ipcc.ch/site/assets/uploads/2018/03/sres-en.pdf)

Adding SRES/Nakicenovic et al., 2000, and augmenting AR4 with multiple chapters

I have completed the following:
- [x] Added SRES, Nakicenovic `sres-wg-iii.bib`
- [x] Fixed trailing {Emilio Lebre}, comma
- [x] added `sres-wg-iii.bib` in `Makefile`
- [x] added AR4 Ch1/Le Treut et al.
- [x] added AR4 Ch3/Trenberth et al.
- [x] added AR4 Ch5/Bindoff et al.
- [x] added AR4 Ch8/Randall et al.
- [x] added AR4 Ch9/Hegerl et al.
- [x] added AR4 Ch10/Meehl et al.
- [ ] Run `Makefile` (`bibtex2html` over updated `*.bib` files)

### PR DESCRIPTION
**Pull request by durack1**
Fix #38 

Adding SRES/Nakicenovic et al., 2000; Augmenting AR4 with additional chapter references

### CODE REVIEW

**Comment by durack1** [comment]
@rgieseke another addition to merge

**Comment by rgieseke** [comment]
Awesome, thank you!
Do you know whether one can safely use " Nakićenović, Nebojša" in BibTeX? 
Then I would probably use that as it's written like that in the PDF.
It seems to work when I run it through `bib2html`. (I had to fix an extra comma after `{Emilio Lebre},`).

**Comment by durack1** [comment]
@rgieseke I think an issue will be the UTF-8erising of this. HTML doesn't play nicely with these special characters, so easiest to avoid them so everything plays nice. On the web (as HTML doesn't like these characters), a search for "nakicenovic" works fine, not sure whether a google scour UTF-8's everything anyway.

FYI, the IPCC page for this UTF-8's it too - https://www.ipcc.ch/report/emissions-scenarios/

**Comment by durack1** [comment]
The other comment, I have imported this into Zotero, and it plays nice, BUT, the default way that tags are assigned means you have two entries for `nakicenovic_overview_2000*` which map to Chapter/Section 2 and 4, and the same for `*summary_2000*` which map to Chapter/Section 6, plus the book entry itself - it's a little clumsy to use in practice, not sure if there is tag control that most software would respect, so rather than having the above, you could have `nakicenovic_summary_2000` (the book), `nakicenovic_SPM_2000`, `nakicenovic_ch6_2000` (for a chapter/section), etc

**Comment by rgieseke** [comment]
>The other comment, I have imported this into Zotero, and it plays nice, BUT, the default way that tags are assigned means you have two entries for nakicenovic_overview_2000* which map to Chapter/Section 2 and 4, and the same for *summary_2000* which map to Chapter/Section 6, plus the book entry itself - it's a little clumsy to use in practice, not sure if there is tag control that most software would respect, so rather than having the above, you could have nakicenovic_summary_2000 (the book), nakicenovic_SPM_2000, nakicenovic_ch6_2000 (for a chapter/section), etc

I'm not sure I follow here. What are the "tags" in Zotero? Do you mean the Bibtex reference identifier/key? Is this getting changed in Zotero due to how Zotero creates these algorithmically?

**Comment by rgieseke** [comment]
>@rgieseke I think an issue will be the UTF-8erising of this. HTML doesn't play nicely with these special characters, so easiest to avoid them so everything plays nice. On the web (as HTML doesn't like these characters), a search for "nakicenovic" works fine, not sure whether a google scour UTF-8's everything anyway.
>
>FYI, the IPCC page for this UTF-8's it too - https://www.ipcc.ch/report/emissions-scenarios/

UTF-8 is actually the encoding to have all accents and chars from many languages included in one HTML page.

I was thinking about UTF-8 compatibility between the different tools for LaTeX, like discussed here: https://tex.stackexchange.com/questions/8411/what-is-the-difference-between-bibtex-and-biblatex

**Comment by rgieseke** [comment]
Related to the question on identifiers. In the SRES report, it's not really a 'collection' like the other reports we have here as the authors are the same for every chapter.

Should these chapters be using `inbook` instead of `incollection`?

**Comment by durack1** [comment]
> I'm not sure I follow here. What are the "tags" in Zotero? Do you mean the Bibtex reference identifier/key? Is this getting changed in Zotero due to how Zotero creates these algorithmically?

Yep, exactly. Upon importing the *.bib into Zotero, the below is what you see, which means the bib defined citation identities e.g., `@incollection{IPCC_2000_SRES_Ch_3,` are being replaced (at least in Zotero, not sure what other packages do)
Screenshot 2024-06-06 at 7 28 09 AM

> UTF-8 is actually the encoding to have all accents and chars from many languages included in one HTML page.

I was too loose with identities here. What I meant was that mapping all characters into the standard 128 ASCII character (python "byte literals" [here](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals)) set [(here, excluding extended chars 128-255)](https://www.ascii-code.com/) is what I had intended to convey. As a python code example, this is what I meant:

```python
>>> import unicodedata
>>> print(unicodedata.normalize("NFKD", "Nakićenović").encode("ascii", "ignore"))
b'Nakicenovic'
```

Wildly speculating, I am guessing this is what most of the web standardizes on, as if you take a look at the IPCC website SRES homepage the "Nebojša Nakićenović" is actually displayed as "Nebojsa Nakicenovic", much like the way that search engines and citation indexes treat this. So simplifying this to the core (0-127 ascii chars) makes sense to me. I have not reviewed other existing *.bib files in this repo to see what has been done before.

**UPDATE:** it seems this impacts `ar6-wg-i` entries alone - I am using `ar4-wg-i`, `ar6-wg-i`, `far-wg-i`, `sar-wg-i`, `sres-wg-iii`, `tar-wg-i` and searched these for the common é character

> Related to the question on identifiers. In the SRES report, it's not really a 'collection' like the other reports we have here as the authors are the same for every chapter.
> 
> Should these chapters be using `inbook` instead of `incollection`?

I think you're right, from the biblatex manual ([here](https://mirrors.ibiblio.org/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf#page=9))

```python
book A single-volume book with one or more authors where the authors share credit for the work
as a whole. This entry type also covers the function of the @inbook type of traditional BibTeX,
see § 2.3.1 for details.
```
```python
collection A single-volume collection with multiple, self-contained contributions by distinct
authors which have their own title. The work as a whole has no overall author but it will usually
have an editor.
```

Will make that change `incollection` -> `inbook`

**Comment by durack1** [comment]
@rgieseke a slightly tricky one is that the SPM has an independent ISBN, compared to the full 6 chapter (+ annexes/appendices) report. My update includes this as an `@inbook` and a separate URL but this is a little misleading. Having said all that, good enough for me! Feel free to merge if you see nothing wrong with this, I'll start using my version.

**Comment by rgieseke** [comment]
Thank you! I reverted the `@inbook` usage as this caused even more warnings (see also #20).
I also removed the `pp` in the pages field as they showed up as "pages pp. 123" in the rendered output and went with "Nebojša Nakićenović". I hope people using this in the 21st century are able to use UTF-8 supporting TeX tools :smiley:

**Comment by rgieseke** [comment]
FWIW, on the `@inbook` issue, it might be possible to solve but maybe it's easier to stick with what we have now in the repo for the other reports.

See also this from the Bibtex docs (taken from https://tex.stackexchange.com/questions/103425/bibtex-author-and-editor-inbook):

>  The standard style’s thirteen entry types do reasonably well at formatting most entries, but no scheme with just thirteen formats can do everything perfectly. Thus, you should feel free to be creative in how you use these entry types (but if you have to be too creative, there's a good chance you're using the wrong entry type).
> 
> Don't take the ﬁeld names too seriously. Sometimes, for instance, you might have to include the publisher's address along with the publisher's name in the publisher ﬁeld, rather than putting it in the address ﬁeld. Or sometimes, difficult entries work best when you make judicious use of the note ﬁeld.
> 
> Don't take the warning messages too seriously. Sometimes, for instance, the year appears in the title, as in The 1966 World Gnus Almanac. In this case it's best to omit the year ﬁeld and to ignore BibTEX’s warning message.
>

**Comment by durack1** [comment]
@rgieseke That sounds good; I'll pull down your merge and take a peek. Thanks for catching the `pp` repetition. I just checked, and this is a problem in rendered output for me, too, so thanks for highlighting it. Did you fix it across the entire repo, or just SRES, as I added the `pp` across many of my contributions? Oops.

**UPDATE: looks like you've caught this across the repo, great**

On the `@inbook` issue, I have an interesting one for you. [CLIVAR Exchanges](https://www.clivar.org/publications/exchanges) have been used readily by the community to capture information about evolving projects and meeting reports, which are the only source of information about model intercomparison projects (MIPs) in decades gone by. For e.g., for CMIP5, there was a [CMIP5 Special Issue](https://www.clivar.org/sites/default/files/documents/Exchanges56.pdf#page=20), which is the only "definitive" resource that exists to define CFMIP-2/Bony et al., 2011. How would you suggest these are captured, `@incollection`?

**Comment by rgieseke** [comment]
> On the @inbook issue, I have an interesting one for you. [CLIVAR Exchanges](https://www.clivar.org/publications/exchanges) have been used readily by the community to capture information about evolving projects and meeting reports, which are the only source of information about model intercomparison projects (MIPs) in decades gone by. For e.g., for CMIP5, there was a [CMIP5 Special Issue](https://www.clivar.org/sites/default/files/documents/Exchanges56.pdf#page=20), which is the only "definitive" resource that exists to define CFMIP-2/Bony et al., 2011. How would you suggest these are captured, @incollection?

Interesting question, it seems these are referenced as articles, e.g. from Google Scholar:

```bibtex
@article{stouffer2011cmip5,
  title={CMIP5 long-term experimental design},
  author={Stouffer, Ronald J and Taylor, Karl E and Meehl, Gerald A},
  journal={CLIVAR Exchanges},
  volume={56},
  number={16},
  pages={2},
  year={2011},
  publisher={International CLIVAR Project Office Southampton, United Kingdom}
}
```

CLIVAR Exchange being treated the journal. It seems they only hand out DOIs for the issue (for the newer ones).

**Comment by durack1** [comment]
Interesting. The CLIVAR Exchanges issues often have a title or focus, with the one above being the CMIP5 special issue, which I encoded the same article as below:

```python
@incollection{stouffer_cmip5_2011,
    author = {Stouffer, {Ronald J.} and Taylor, {Karl E.} and Meehl, {Gerald A.}},
    title = {CMIP5 Long-term experimental Design},
    booktitle = {Special Issue: WCRP Coupled Model Intercomparison Project - Phase 5 - CMIP5 -},
    year = {2011},
    url = {https://www.clivar.org/sites/default/files/documents/Exchanges56.pdf#Page=5},
    doi = {},
    editor = {Pirani, Anna},
    pages = {5-7},
    publisher = {CLIVAR},
    type = {Article},
    address = {International CLIVAR Project Office, Southampton, UK}
}
```
The pdf linked above has number, volume, number identified. With the first number most often sequentional (1 - Feb 1996 through 82 - Nov 2022), which makes it a little hard to fit into the standard article formatting. Many of these are special issues, the No.56 above is the CMIP5 special issue, and No.82 is the Special Issue: Tropical Atlantic Ocean
Observing System (TAOS). There are often also meeting reports etc contained in each issue, which replicates (in some way) what BAMS provides, although BAMS most often have a dedicated DOI for each article/meeting report etc.

Most journals follow a [Volume | Issue | Number] system, so it's a little hard to figure out how to map the [Number | Issue | Number] identities which are common across CLIVAR Exchange editions

**Pull request merged**
