### PR TITLE
Complete the AR6 WG2 bib file

### PR DESCRIPTION
**Pull request by pitmonticone**
I've enriched and standardised the AR6 WG2 citation file adopting the following scheme obtained by integrating and fixing the entries contained in the [official citation files](https://github.com/openclimatedata/ipcc-bibtex/issues/25): 

```bib 
# Full Report

@book{IPCC_YEAR_WGX,
    address = {Cambridge, UK and New York, NY, USA},
    author = {IPCC},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book},
    url = {},
    year = {YEAR}
}

# Summary for Policymakers

@incollection{IPCC_YEAR_WGX_SPM,
    address = {Cambridge, UK and New York, NY, USA},
    author = {IPCC},
    booktitle = {},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {Summary for Policymakers},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Technical Summary

@incollection{IPCC_YEAR_WGX_TS,
    address = {Cambridge, UK and New York, NY, USA},
    author = {},
    booktitle = {},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {Technical Summary},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Chapters 

@incollection{IPCC_YEAR_WGX_Ch_Y,
    address = {Cambridge, UK and New York, NY, USA},
    author = {},
    booktitle = {},
    chapter = {},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Chapters Supplementary Material 

@incollection{IPCC_YEAR_WGX_Ch_Y_SM,
    address = {Cambridge, UK and New York, NY, USA},
    author = {},
    booktitle = {},
    chapter = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Cross-Chapter Papers 

@incollection{IPCC_YEAR_WGX_CCP_Y,
    address = {Cambridge, UK and New York, NY, USA},
    author = {},
    booktitle = {},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Cross-Chapter Papers Supplementary Material 

@incollection{IPCC_YEAR_WGX_CCP_Y_SM,
    address = {Cambridge, UK and New York, NY, USA},
    author = {},
    booktitle = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book Section},
    url = {},
    year = {YEAR}
}

# Annexes

@incollection{IPCC_YEAR_WGX_Annex_Y,
    address = {Cambridge, UK and New York, NY, USA},
    author = {IPCC},
    booktitle = {},
    chapter = {Annex Y},
    doi = {},
    editor = {},
    publisher = {Cambridge University Press},
    title = {},
    type = {Book Section},
    url = {},
    year = {YEAR}
}
```

The same scheme will be applied to the WG1 citation file in the next few days. 

CC: @rgieseke @jkikstra

### CODE REVIEW

**Comment by rgieseke** [comment]
Thank you! Live here: https://openclimatedata.github.io/ipcc-bibtex/ar6-wg-ii.html

**Comment by rgieseke** [comment]
Can you start a new PR branching off from the main branch if you work on WGI? Otherwise it gets tricky to merge.
I've cherry-picked WGII here: https://github.com/openclimatedata/ipcc-bibtex/commit/57a393ffe7b43d4211043fe69f59a08ed2aad212

**Comment by pitmonticone** [comment]
Sure @rgieseke, I'm sorry for the inconvenience. I'll create a new dedicated branch for the next PR.

**Comment by rgieseke** [comment]
No worries, it was just one command!

**Pull request closed without merging**
