### PR TITLE
Add first half of ar6 wg3 citations

### PR DESCRIPTION
**Pull request by jkikstra**
Makes a first start of adding WG3 citations.

Has full report, SPM, TM, Chapters 1-8, and Annex I-III.

Still missing everything from Chapter 9 to Chapter 17 SM.

### CODE REVIEW

**Comment by rgieseke** [comment]
Wicked, thanks!

Is Lwasa2022(a) the same, right? The DOI is also not yet resolving.

**Comment by rgieseke** [comment]
Got it, it's the Supplementary Material!

**Comment by rgieseke** [comment]
I've changed the BibTeX keys to be a bit more inline with the style in the other files, thanks again, that's awesome!!

HTML preview also updated, should be up in a bit https://openclimatedata.github.io/citations/

**Comment by znicholls** [comment]
@jkikstra how did you work this all out so fast? WG1 still doesn't have DOIs as far as I can tell...

**Comment by jkikstra** [comment]
Yeah I'm not sure what's up with WG I being so slow on that...

But basically I manually created entries in Mendeley based on this https://report.ipcc.ch/ar6wg3/pdf/IPCC_AR6_WGIII_Citation.pdf

**Comment by rgieseke** [comment]
Good to know!
Maybe we should add this and https://report.ipcc.ch/ar6wg1/pdf/IPCC_AR6_WGI_Citation.pdf to the Readme ...

**Comment by rgieseke** [comment]
And https://report.ipcc.ch/ar6wg2/pdf/IPCC_AR6_WGII_Citation.pdf

**Comment by znicholls** [comment]
Would be super helpful (or we just put them in an issue for a day when one of us is bored to type up)

I honestly can't understand why WG3 has DOIs, WG1 doesn't etc. but not my problem to solve I guess

**Comment by rgieseke** [comment]
IIRC in AR5 WG1 was the only one to have some DOIs. :man_shrugging:

**Comment by rgieseke** [comment]
Also they don't resolve yet ...

**Pull request merged**
